name: Env specific - Deploy Web Application to Azure Web App

on:
   push:
     branches:
       - "develop"
   workflow_dispatch:

env:
  DOTNET_VERSION: "6.0.x"
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  env-name: "-na-"

defaults:
  run:
    working-directory: ./webapplication01

jobs:
  decide-env:
    runs-on: windows-latest
    outputs:
       selected-stage: ${{ steps.select-env.outputs.selected-stage }}
    steps:
       - uses: actions/checkout@v3
       
       - name: Decide deployment environment
         id: select-env
         shell: bash
         run: |
           if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
           echo "develop"
           echo "selected-stage=develop" >> "$GITHUB_OUTPUT"
           elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
           echo "test"
           echo "selected-stage=test" >> "$GITHUB_OUTPUT"
           elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
           echo "production"
           echo "selected-stage=prod" >> "$GITHUB_OUTPUT"
           else
           echo "feature-branch"
           echo "selected-stage=feature" >> "$GITHUB_OUTPUT"
           fi

  build:
    runs-on: windows-latest
    needs: decide-env
    steps:
      - uses: actions/checkout@v3

      - name: Set up .Net Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Publish Project
        run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/webapp

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: .net-application
          path: ${{ env.DOTNET_ROOT }}/webapp

  deploy:
    name: Deploy to ${{ needs.decide-env.outputs.selected-stage }} environment
    runs-on: windows-latest
    permissions:
      contents: none
    needs: [decide-env, build]
    #if: needs.decide-env.outputs.selected-stage == 'develop'
    environment:
      name: ${{ needs.build.outputs.selected-stage }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    env:
      APPSETTINGS_PATH: appsettings.json
      AZURE_WEBAPP_NAME: netcorewebapp01    # set this to the name of your Azure Web App
      env_value: ${{ needs.decide-env.outputs.selected-stage }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-application
      
      #- name: Display Environment Value
      #  shell: bash
      #  run: echo "Environment Value ${{ env.env_value }}"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
