name: Env specific - Deploy Web Application to Azure Web App

on:
  # push:
  #   branches:
  #     - "main"
  workflow_dispatch:
    inputs:
        deploy_env:
          description: Select Env
          type: choice
          options:
            - develop
            - integration
            - prod
          required: true
          default: develop
env:
  DOTNET_VERSION: "6.0.x"
  #AZURE_WEBAPP_NAME: netcorewebapp02    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

# defaults:
#   run:
#     working-directory: ./webapplication01

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Set up .Net Core
      #   uses: actions/setup-dotnet@v2
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}

      # - name: Install Dependencies
      #   run: dotnet restore

      # - name: Build Project
      #   run: dotnet build --configuration Release

      # - name: Publish Project
      #   run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/webapp

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: .net-app
      #     path: ${{ env.DOTNET_ROOT }}/webapp

  deploy:
    name: Deploy to ${{ github.ref_name == 'main' && 'prod' || github.ref_name }} environment
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    if: contains(fromJSON('["develop", "integration", "main"]'), github.ref_name) 
    env: 
      # AZURE_REGION:  ${{ github.ref_name }}_REGION
      # AZURE_VMNAME:  ${{ github.ref_name }}_VMNAME
      # AZURE_CLIENTID:  ${{ github.ref_name }}_CLIENTID
      AZURE_REGION:  ${{ github.event.inputs.deploy_env }}_REGION
      AZURE_VMNAME:  ${{ github.event.inputs.deploy_env }}_VMNAME
      AZURE_CLIENTID:  ${{ github.event.inputs.deploy_env }}_CLIENTID
      
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: .net-app

      - name: Validate the ENV. Values & Secrets
        shell: bash
        run: |
          echo "NEW_VAR = " ${{ vars.NEW_VAR }}
          echo "AZURE_REGION = " ${{ vars.AZURE_REGION }}
          echo "AZURE_VMNAME = " ${{ vars.AZURE_VMNAME }}
          echo AZURE_CLIENTID = ${{ secrets[vars.AZURE_CLIENTID] }}
          echo "NEW_VAR = $NEW_VAR"
          echo "AZURE_REGION = $AZURE_REGION"
          echo "AZURE_VMNAME = $AZURE_VMNAME"
          echo "AZURE_CLIENTID = $AZURE_CLIENTID"

      # - name: Deploy to Azure Web App
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
