name: Env specific - Deploy Web Application to Azure Web App

on:
   push:
     branches:
       - "develop"
   workflow_dispatch:

env:
  DOTNET_VERSION: "6.0.x"
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  env-name: "-na-"

defaults:
  run:
    working-directory: ./webapplication01

jobs:
  decide-env:
    runs-on: windows-latest
    outputs:
       selected-stage: ${{ steps.select-env.outputs.selected-stage }}
    steps:
       - uses: actions/checkout@v3
       
       - name: Display Values
         shell: bash
         run: |
           #echo ${{ github.head_ref }}
           echo ${{ github.ref_name }}
           #echo "selected-stage=develop" >> "$GITHUB_OUTPUT"

