name: Deploy Web Application to Azure Web App

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  DOTNET_VERSION: "6.0.x"
  AZURE_WEBAPP_NAME: netcorewebapp01    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

defaults:
  run:
    working-directory: ./webapplication01

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up .Net Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Publish Project
        run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/webapp

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: .net-application
          path: ${{ env.DOTNET_ROOT }}/webapp

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-application

      - uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Update App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          mask-inputs: false
          app-settings-json: '[{ "name": "DisplayEnvironment", "value": ${{vars.DisplayEnvironment}}, "slotSetting": false }]'
          id: settings
          
      - run: echo "The webapp-url is ${{ steps.settings.outputs.webapp-url }}"
      - run: |
          az logout
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
